apiVersion: v1
kind: Service
metadata:
  name: mlflow-gcp-service
  labels:
    run: mlflow-gcp-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: mlflow-gcp