apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-gcp-deploy
  labels:
    app: mlflow-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-gcp
  template:
    metadata:
      labels:
        app: mlflow-gcp
    spec:
      containers:
      - name: mlflow-gcp
        image: arunma/mlflow-gcp
        env:
        - name: GCLOUD_SERVICE_KEY_ENC
          valueFrom:
            secretKeyRef:
              name: mlflow-env-secret
              key: GCLOUD_SERVICE_KEY_ENC
        - name: GCP_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: mlflow-env-secret
              key: GCP_STORAGE_BUCKET
        command: ["/start.sh"]
